/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.segundoproyecto.configuracion;
import com.mycompany.segundoproyecto.funciones.Personaje;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedWriter;
import java.io.File;


import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


/**
 *
 * @author jecheverria
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        txf_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        txf_vida = new javax.swing.JTextField();
        lbl_vida = new javax.swing.JLabel();
        txf_daño = new javax.swing.JTextField();
        lbl_daño = new javax.swing.JLabel();
        txf_nvlAparicion = new javax.swing.JTextField();
        lbl_nvlAparicion = new javax.swing.JLabel();
        cb_tiposPersonaje = new javax.swing.JComboBox<>();
        lbl_tipoPersonaje = new javax.swing.JLabel();
        lbl_TipoAtaque = new javax.swing.JLabel();
        cb_tiposdeAtaque = new javax.swing.JComboBox<>();
        lbl_AparienciaMoviendose = new javax.swing.JLabel();
        btn_crear = new javax.swing.JButton();
        txf_alcance = new javax.swing.JTextField();
        lbl_alcance = new javax.swing.JLabel();
        txf_aparienciaMoviendose = new javax.swing.JTextField();
        btn_guardarMoviendose = new javax.swing.JButton();
        lbl_imageMoviendose = new javax.swing.JLabel();
        lbl_AparienciaAtacando = new javax.swing.JLabel();
        txf_aparienciaAtacando = new javax.swing.JTextField();
        btn_guardarAtacando = new javax.swing.JButton();
        lbl_imageAtacando = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_nombreActionPerformed(evt);
            }
        });

        lbl_nombre.setText("Nombre");

        txf_vida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_vidaActionPerformed(evt);
            }
        });

        lbl_vida.setText("Vida");

        txf_daño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_dañoActionPerformed(evt);
            }
        });

        lbl_daño.setText("Daño");

        txf_nvlAparicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_nvlAparicionActionPerformed(evt);
            }
        });

        lbl_nvlAparicion.setText("Nivel de Aparicion");

        cb_tiposPersonaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defensa", "Zombie" }));
        cb_tiposPersonaje.setSelectedIndex(-1);
        cb_tiposPersonaje.setToolTipText("");
        cb_tiposPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tiposPersonajeActionPerformed(evt);
            }
        });

        lbl_tipoPersonaje.setText("Tipo de Personaje");

        lbl_TipoAtaque.setText("Tipo de Ataque");

        cb_tiposdeAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tiposdeAtaqueActionPerformed(evt);
            }
        });

        lbl_AparienciaMoviendose.setText("Apariencia moviendose");

        btn_crear.setText("Generar");
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        txf_alcance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_alcanceActionPerformed(evt);
            }
        });

        lbl_alcance.setText("Alcance");

        txf_aparienciaMoviendose.setText("C:\\Users\\Jecheverria\\Personajes\\Zombie1.png");
        txf_aparienciaMoviendose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_aparienciaMoviendoseActionPerformed(evt);
            }
        });

        btn_guardarMoviendose.setText("Ver");
        btn_guardarMoviendose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarMoviendoseActionPerformed(evt);
            }
        });

        lbl_AparienciaAtacando.setText("Apariencia atacando");

        txf_aparienciaAtacando.setText("C:\\Users\\Jecheverria\\Personajes\\Zombie1.png");
        txf_aparienciaAtacando.setToolTipText("");
        txf_aparienciaAtacando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_aparienciaAtacandoActionPerformed(evt);
            }
        });

        btn_guardarAtacando.setText("Ver");
        btn_guardarAtacando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarAtacandoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_tiposdeAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_vida, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_vida)
                    .addComponent(txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombre)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_daño)
                        .addComponent(lbl_nvlAparicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txf_nvlAparicion)
                        .addComponent(txf_daño, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_alcance)
                    .addComponent(txf_alcance, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tipoPersonaje)
                    .addComponent(cb_tiposPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TipoAtaque)
                    .addComponent(btn_crear))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lbl_AparienciaAtacando)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_guardarAtacando, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txf_aparienciaAtacando, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_AparienciaMoviendose)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_guardarMoviendose, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txf_aparienciaMoviendose, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lbl_imageMoviendose, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_imageAtacando, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lbl_vida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_daño)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txf_daño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_nvlAparicion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txf_nvlAparicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_alcance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txf_alcance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_AparienciaMoviendose, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_guardarMoviendose))
                        .addGap(9, 9, 9)
                        .addComponent(txf_aparienciaMoviendose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_imageMoviendose, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_AparienciaAtacando, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_guardarAtacando))
                        .addGap(9, 9, 9)
                        .addComponent(txf_aparienciaAtacando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_tipoPersonaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_tiposPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_TipoAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(cb_tiposdeAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btn_crear))
                    .addComponent(lbl_imageAtacando, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_nombreActionPerformed

    private void txf_vidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_vidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_vidaActionPerformed

    private void txf_dañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_dañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_dañoActionPerformed

    private void txf_nvlAparicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_nvlAparicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_nvlAparicionActionPerformed

    private void cb_tiposPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tiposPersonajeActionPerformed

        if (cb_tiposPersonaje.getSelectedIndex() == 0){//Defensa
            cb_tiposdeAtaque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contacto", "Mediano alcance", "Aéreos", "Impacto","Ataque multiple", "Bloque"}));
            cb_tiposdeAtaque.setSelectedIndex(-1);             
            
}
        if (cb_tiposPersonaje.getSelectedIndex() == 1){//Zombie
            cb_tiposdeAtaque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contacto", "Mediano alcance", "Aéreos", "Impacto" }));
            cb_tiposdeAtaque.setSelectedIndex(-1);

}
// TODO add your handling code here:
    }//GEN-LAST:event_cb_tiposPersonajeActionPerformed

    private void cb_tiposdeAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tiposdeAtaqueActionPerformed
        if (cb_tiposPersonaje.getSelectedIndex() == 0){//Defensa

            if (cb_tiposdeAtaque.getSelectedIndex() == 0){//Contacto
                txf_daño.setEditable(true);   
    
                txf_alcance.setText("1");
                txf_alcance.setEditable(false);
            }
            
            if (cb_tiposdeAtaque.getSelectedIndex() == 1 | cb_tiposdeAtaque.getSelectedIndex() == 4){//Mediano alcance o ataque multiple 
                txf_alcance.setEnabled(true);
                txf_alcance.setEditable(true);
            }
            
            if (cb_tiposdeAtaque.getSelectedIndex()== 2){//Aereo
                txf_alcance.setText("0");
                txf_alcance.setEditable(false);
            }

            if (cb_tiposdeAtaque.getSelectedIndex()== 3){//Impacto(Kamikaze?)
                txf_alcance.setText("1");
                txf_alcance.setEditable(false);
            }           
            
            if (cb_tiposdeAtaque.getSelectedIndex() == 5){//Bloque
                txf_alcance.setText("0");
                txf_alcance.setEditable(false);

                txf_daño.setText("0");
                txf_daño.setEditable(false);
            }   
        }
        
        if (cb_tiposPersonaje.getSelectedIndex() == 1){//ZOmbie
            if (cb_tiposdeAtaque.getSelectedIndex()== 0){//Contacto
                txf_alcance.setText("1");
                txf_alcance.setEditable(false);
            }
        
            if (cb_tiposdeAtaque.getSelectedIndex()== 1){//Mediano alcance
                txf_alcance.setEnabled(true);
                txf_alcance.setEditable(true);
            }

            if (cb_tiposdeAtaque.getSelectedIndex()== 2){//Aereo
                txf_alcance.setText("0");
                txf_alcance.setEditable(false);
            }

            if (cb_tiposdeAtaque.getSelectedIndex()== 3){//Impacto(Kamikaze?)
                txf_alcance.setText("1");
                txf_alcance.setEditable(false);

            }
        
        
        
        }//Termina la condicion de los tipos de ataque del zombie
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tiposdeAtaqueActionPerformed

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        boolean errores = false;
        
        //TODO mandar los errores en la pantalla(ventana)
        
        String personaje_str = "%";
            int tipo = cb_tiposPersonaje.getSelectedIndex();
            int tipo_de_ataque = cb_tiposdeAtaque.getSelectedIndex();
            switch (tipo){
                
                case 1://Se eligio zombie(Se escribe una Z)
                    personaje_str += "Z/";
                    switch (tipo_de_ataque){
                        case -1 -> {
                            errores = true;
                            System.out.println("No se eligio el tipo de ataque del zombie");}
                        
                        case 0 -> personaje_str += "C/";
                        
                        case 1 -> personaje_str += "MA/";
                        
                        case 2 -> personaje_str += "A/";
                        
                        case 3 -> personaje_str += "I/";
                    
                    }//Final del switch para el tipos da ataque de zombie
                    break;

                    
                case 0://Se eligio una defensa(Se escribe una D)
                    
                    personaje_str += "D/";
                    switch (tipo_de_ataque){
                        case -1 -> {
                            errores = true;
                            System.out.println("No se eligio el tipo de ataque del defensa");}
                        
                        case 0 -> personaje_str += "C/";
                        
                        case 1 -> personaje_str += "MA/";
                        
                        case 2 -> personaje_str += "A/";
                        
                        case 3 -> personaje_str += "I/";
 
                        case 4 -> personaje_str += "AM/";
                        
                        case 5 -> personaje_str += "B/";
                            
                    }//Final del switch de tipo de ataque de la defensa
                    break;

                case -1:
                    System.out.println("NO SE HA SELECCIONADO UN TIPO DE PERSONAJE");
                    errores = true;
                    break;
            }
            
            //Nombre del personaje
            if (txf_nombre.getText().length() == 0){
                errores = true;
                System.out.println("Su personaje ocupa un nombre");
            }
            else
                personaje_str += txf_nombre.getText()+ "/";
            
            //Vida del personaje
            try{
                Integer.parseInt(txf_vida.getText());
                personaje_str += txf_vida.getText()+ "/" ;
            }
            catch (Exception e){
                errores = true;
                System.out.println("Casilla de vida invalida");
            }
            
            //Daño del personaje
            try{
                Integer.parseInt(txf_daño.getText());
                personaje_str += txf_daño.getText()+ "/";
            }
            catch (Exception e){
                System.out.println("Casilla de daño invalida");
                errores = true;
            }
            

            
            //Nivel de aparicion 
            try{               
                Integer.parseInt(txf_nvlAparicion.getText());
                personaje_str += txf_nvlAparicion.getText()+"/";
            }
            catch (Exception e){
                errores = true;        
                System.out.println("Casilla de nivel de aparicion invalida");
            }
            
            //Alcance del perosnaje
            try{               
                Integer.parseInt(txf_alcance.getText());
                personaje_str += txf_nvlAparicion.getText()+"/";
            }
            catch (Exception e){
                errores = true;        
                System.out.println("Casilla de nivel de aparicion invalida");
            }
            
            //Apariencia del personaje moviendose (direccion de imagen
            if (txf_aparienciaMoviendose.getText().length() == 0){
                errores = true;
                System.out.println("Su personaje ocupa un apariencia");
            }
            else{
                personaje_str += txf_aparienciaMoviendose.getText()+ "/";
            }
            
            
            //Apariencia del personaje atacando(direccion de imagen)
            if (txf_aparienciaAtacando.getText().length() == 0 & txf_aparienciaMoviendose.getText().length() != 0){
                personaje_str += txf_aparienciaMoviendose.getText();
            }
            else{
                personaje_str += txf_aparienciaAtacando.getText();
            }
            
            if (!errores){
                System.out.println(personaje_str);
                FileWriter escritor;
                try {
                    escritor = new FileWriter("Personajes.txt",true); 
                    escritor.write(personaje_str);
                    escritor.close();
                } catch (IOException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }           
            }
           
// TODO add your handling code here:
    }//GEN-LAST:event_btn_crearActionPerformed

    private void txf_alcanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_alcanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_alcanceActionPerformed

    private void txf_aparienciaMoviendoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_aparienciaMoviendoseActionPerformed
        



        // TODO add your handling code here:
    }//GEN-LAST:event_txf_aparienciaMoviendoseActionPerformed

    private void btn_guardarMoviendoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarMoviendoseActionPerformed
        if (txf_aparienciaMoviendose.getText() == null ){
        System.out.println("Ingrese el directorio donde se ecuentra la apariencia de su personaje");
    }
        else{
            try{
                //lbl_image.setIcon(new javax.swing.ImageIcon());
                 
                BufferedImage bufferedImage;
                bufferedImage = ImageIO.read(new File(txf_aparienciaMoviendose.getText()));
                Image image = bufferedImage.getScaledInstance(150, 150, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(image);
                lbl_imageMoviendose.setIcon((icon));
                System.out.println(txf_aparienciaMoviendose.getText());
            }catch(Exception e){
                System.out.println("No se encontro la imagen en la direccion");
            }
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarMoviendoseActionPerformed

    private void txf_aparienciaAtacandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_aparienciaAtacandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_aparienciaAtacandoActionPerformed

    private void btn_guardarAtacandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarAtacandoActionPerformed
        if (txf_aparienciaAtacando.getText() == null ){
        System.out.println("Ingrese el directorio donde se ecuentra la apariencia de su personaje");
    }
        else{
            try{
                //lbl_image.setIcon(new javax.swing.ImageIcon());
                 
                BufferedImage bufferedImage;
                bufferedImage = ImageIO.read(new File(txf_aparienciaAtacando.getText()));
                Image image = bufferedImage.getScaledInstance(150, 150, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(image);
                lbl_imageAtacando.setIcon((icon));
                System.out.println(txf_aparienciaAtacando.getText());
            }catch(Exception e){
                System.out.println("No se encontro la imagen en la direccion");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarAtacandoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_crear;
    public javax.swing.JButton btn_guardarAtacando;
    public javax.swing.JButton btn_guardarMoviendose;
    public javax.swing.JComboBox<String> cb_tiposPersonaje;
    public javax.swing.JComboBox<String> cb_tiposdeAtaque;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    public javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    public javax.swing.JLabel lbl_AparienciaAtacando;
    public javax.swing.JLabel lbl_AparienciaMoviendose;
    public javax.swing.JLabel lbl_TipoAtaque;
    public javax.swing.JLabel lbl_alcance;
    public javax.swing.JLabel lbl_daño;
    public javax.swing.JLabel lbl_imageAtacando;
    public javax.swing.JLabel lbl_imageMoviendose;
    public javax.swing.JLabel lbl_nombre;
    public javax.swing.JLabel lbl_nvlAparicion;
    public javax.swing.JLabel lbl_tipoPersonaje;
    public javax.swing.JLabel lbl_vida;
    public javax.swing.JTextField txf_alcance;
    public javax.swing.JTextField txf_aparienciaAtacando;
    public javax.swing.JTextField txf_aparienciaMoviendose;
    public javax.swing.JTextField txf_daño;
    public javax.swing.JTextField txf_nombre;
    public javax.swing.JTextField txf_nvlAparicion;
    public javax.swing.JTextField txf_vida;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JComboBox<String> cb_tiposdeZombies;
    public javax.swing.JLabel lbl_tipoZombie;
    public javax.swing.JPanel pnl_tipoDeZombie;

}