/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.segundoproyecto.configuracion;
import com.mycompany.segundoproyecto.funciones.Personaje;
/**
 *
 * @author jecheverria
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        txf_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        txf_vida = new javax.swing.JTextField();
        lbl_vida = new javax.swing.JLabel();
        txf_daño = new javax.swing.JTextField();
        lbl_daño = new javax.swing.JLabel();
        txf_nvlAparicion = new javax.swing.JTextField();
        lbl_nvlAparicion = new javax.swing.JLabel();
        cb_tiposPersonaje = new javax.swing.JComboBox<>();
        lbl_tipoPersonaje = new javax.swing.JLabel();
        lbl_TipoAtaque = new javax.swing.JLabel();
        cb_tiposdeAtaque = new javax.swing.JComboBox<>();
        lbl_Apariencia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_nombreActionPerformed(evt);
            }
        });

        lbl_nombre.setText("Nombre");

        txf_vida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_vidaActionPerformed(evt);
            }
        });

        lbl_vida.setText("Vida");

        txf_daño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_dañoActionPerformed(evt);
            }
        });

        lbl_daño.setText("Daño");

        txf_nvlAparicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_nvlAparicionActionPerformed(evt);
            }
        });

        lbl_nvlAparicion.setText("Nivel de Aparicion");

        cb_tiposPersonaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Defensa", "Zombie" }));
        cb_tiposPersonaje.setSelectedIndex(-1);
        cb_tiposPersonaje.setToolTipText("");
        cb_tiposPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tiposPersonajeActionPerformed(evt);
            }
        });

        lbl_tipoPersonaje.setText("Tipo de Personaje");

        lbl_TipoAtaque.setText("Tipo de Ataque");

        cb_tiposdeAtaque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contacto", "Mediano alcance", "Aéreos", "Impacto", "Ataque múltiple", "Bloques" }));
        cb_tiposdeAtaque.setSelectedIndex(-1);
        cb_tiposdeAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tiposdeAtaqueActionPerformed(evt);
            }
        });

        lbl_Apariencia.setText("Apariencia");

        jLabel2.setText("Imagen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_nombre))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_tipoPersonaje)
                                    .addComponent(cb_tiposPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl_daño)
                                        .addComponent(lbl_nvlAparicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txf_nvlAparicion)
                                        .addComponent(txf_daño)
                                        .addComponent(txf_vida, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_vida))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_TipoAtaque)
                                    .addComponent(cb_tiposdeAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Apariencia))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_TipoAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cb_tiposdeAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_vida)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txf_vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(lbl_daño)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_daño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_nvlAparicion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_nvlAparicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_tipoPersonaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_tiposPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_Apariencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_nombreActionPerformed

    private void txf_vidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_vidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_vidaActionPerformed

    private void txf_dañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_dañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_dañoActionPerformed

    private void txf_nvlAparicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_nvlAparicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_nvlAparicionActionPerformed

    private void cb_tiposPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tiposPersonajeActionPerformed
        if (cb_tiposPersonaje.getSelectedIndex() == -1){
        }
        
        if (cb_tiposPersonaje.getSelectedIndex() == 0){//Defensa

}
if (cb_tiposPersonaje.getSelectedIndex() == 1){//Zombie
      /*  pnl_tipoDeDefensa = new javax.swing.JPanel();
        lbl_defensa = new javax.swing.JLabel();
        cb_tiposdeZombies = new javax.swing.JComboBox<>();
        cb_tiposdeZombies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contacto", "Mediano alcance", "Aéreos", "Impacto" }));
        cb_tiposdeZombies.setSelectedIndex(-1);

        lbl_tipoZombie.setText("Tipo de Zombie");

        javax.swing.GroupLayout pnl_tipoDeZombieLayout = new javax.swing.GroupLayout(pnl_tipoDeZombie);
        pnl_tipoDeZombie.setLayout(pnl_tipoDeZombieLayout);
        pnl_tipoDeZombieLayout.setHorizontalGroup(
            pnl_tipoDeZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tipoDeZombieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_tipoDeZombieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tipoZombie)
                    .addComponent(cb_tiposdeZombies, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );*/
}
// TODO add your handling code here:
    }//GEN-LAST:event_cb_tiposPersonajeActionPerformed

    private void cb_tiposdeAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tiposdeAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_tiposdeAtaqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> cb_tiposPersonaje;
    public javax.swing.JComboBox<String> cb_tiposdeAtaque;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    public javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    public javax.swing.JLabel lbl_Apariencia;
    public javax.swing.JLabel lbl_TipoAtaque;
    public javax.swing.JLabel lbl_daño;
    public javax.swing.JLabel lbl_nombre;
    public javax.swing.JLabel lbl_nvlAparicion;
    public javax.swing.JLabel lbl_tipoPersonaje;
    public javax.swing.JLabel lbl_vida;
    public javax.swing.JTextField txf_daño;
    public javax.swing.JTextField txf_nombre;
    public javax.swing.JTextField txf_nvlAparicion;
    public javax.swing.JTextField txf_vida;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JComboBox<String> cb_tiposdeZombies;
    public javax.swing.JLabel lbl_tipoZombie;
    public javax.swing.JPanel pnl_tipoDeZombie;

}