/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.segundoproyecto.configuracion;

import com.mycompany.segundoproyecto.ThreadCaminar;
import com.mycompany.segundoproyecto.ThreadInformacion;
import javax.swing.JLabel;

/**
 *
 * @author PC
 */
public class VentanaInformacion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInformacion
     */
    public VentanaInformacion(int i,int j) {
        initComponents();
        ThreadInformacion tr = new ThreadInformacion(this, i,j);
        tr.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nombre = new javax.swing.JLabel();
        lbl_nvlAparicion = new javax.swing.JLabel();
        lbl_vida = new javax.swing.JLabel();
        lbl_daño = new javax.swing.JLabel();
        lbl_TipoAtaque = new javax.swing.JLabel();
        lbl_vidaDato = new javax.swing.JLabel();
        lbl_nvlAparicionDato = new javax.swing.JLabel();
        lbl_dañoDato = new javax.swing.JLabel();
        lbl_TipoAtaqueDato = new javax.swing.JLabel();
        lbl_nombreDato = new javax.swing.JLabel();

        lbl_nombre.setText("Nombre:");

        lbl_nvlAparicion.setText("Nivel de Aparicion:");

        lbl_vida.setText("Vida:");

        lbl_daño.setText("Daño:");

        lbl_TipoAtaque.setText("Tipo de Ataque:");

        lbl_vidaDato.setText("Vida");

        lbl_nvlAparicionDato.setText("Nivel de Aparicion");

        lbl_dañoDato.setText("Daño");

        lbl_TipoAtaqueDato.setText("Tipo de Ataque");

        lbl_nombreDato.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_nvlAparicion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_nvlAparicionDato))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_TipoAtaque)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_TipoAtaqueDato))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_daño)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_dañoDato))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_vida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_vidaDato))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_nombre)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_nombreDato)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(lbl_nombreDato))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_vida)
                    .addComponent(lbl_vidaDato))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TipoAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TipoAtaqueDato, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_daño)
                    .addComponent(lbl_dañoDato))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nvlAparicion)
                    .addComponent(lbl_nvlAparicionDato))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInformacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaInformacion().setVisible(true);
            }
        });
    }*/

    public JLabel getLbl_TipoAtaqueDato() {
        return lbl_TipoAtaqueDato;
    }

  

    public JLabel getLbl_dañoDato() {
        return lbl_dañoDato;
    }

    public JLabel getLbl_nombreDato() {
        return lbl_nombreDato;
    }

    public JLabel getLbl_nvlAparicionDato() {
        return lbl_nvlAparicionDato;
    }

    public JLabel getLbl_vidaDato() {
        return lbl_vidaDato;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_TipoAtaque;
    private javax.swing.JLabel lbl_TipoAtaqueDato;
    private javax.swing.JLabel lbl_daño;
    private javax.swing.JLabel lbl_dañoDato;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_nombreDato;
    private javax.swing.JLabel lbl_nvlAparicion;
    private javax.swing.JLabel lbl_nvlAparicionDato;
    private javax.swing.JLabel lbl_vida;
    private javax.swing.JLabel lbl_vidaDato;
    // End of variables declaration//GEN-END:variables
}
