/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.segundoproyecto.configuracion;

import com.mycompany.segundoproyecto.Datos;
import com.mycompany.segundoproyecto.Funciones;
import com.mycompany.segundoproyecto.funciones.Defensa;
import com.mycompany.segundoproyecto.funciones.Personaje;
import com.mycompany.segundoproyecto.funciones.Zombie;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author jecheverria
 */
public class VentanaResultados extends javax.swing.JFrame {

    /**
     * Creates new form VentanaResultados
     */
    public VentanaResultados() {
        initComponents();
        txa_resultadod.setEditable(false);
        txa_resultadoz.setEditable(false);
        for(Zombie zombie : Datos.ZombiesEnJuego){
            zombie.setRegistro("\n\nNombre: "+ zombie.getNombre()+"\nPosicion: "+ "("+zombie.getPosicion()[0]+","+zombie.getPosicion()[1]+")"
                    +"\nVida: "+zombie.getVida() + "/"+zombie.getVidaOriginal()+zombie.getRegistro());
            if (zombie.getVida()<= 0){
                zombie.setRegistro(zombie.getRegistro()+"\nY lo mató\n");
            }
            txa_resultadoz.setText(txa_resultadoz.getText()+zombie.getRegistro());
        }    

        for(Defensa defensa : Datos.defensasEnJuego){
            defensa.setRegistro("\n\nNombre: "+ defensa.getNombre()+"\nPosicion: "+ "("+defensa.getPosicion()[0]+","+defensa.getPosicion()[1]+")"+
                    "\nVida: "+defensa.getVida() + "/"+defensa.getVidaOriginal()+defensa.getRegistro());
           
            if (defensa.getVida()<= 0){
                defensa.setRegistro(defensa.getRegistro()+"\nY lo mató\n");
            }
            
            txa_resultadod.setText(txa_resultadod.getText()+defensa.getRegistro());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_resultado_zombies = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txa_resultadod = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txa_resultadoz = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane3.setEnabled(false);

        txa_resultadod.setColumns(20);
        txa_resultadod.setRows(5);
        txa_resultadod.setText("Resultados de las defensas:");
        jScrollPane3.setViewportView(txa_resultadod);

        jScrollPane4.setEnabled(false);

        txa_resultadoz.setColumns(20);
        txa_resultadoz.setRows(5);
        txa_resultadoz.setText("Resultados de los zombies:");
        jScrollPane4.setViewportView(txa_resultadoz);

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Repetir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_resultado_zombies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_resultado_zombies)
                .addGap(11, 11, 11))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Funciones.subirnivel();
        
        for (JButton[] jButtons : Datos.matrizBotonesInterfaz) {
            for (JButton jButton : jButtons) {
                jButton.setIcon(null);
            }
            
        }
        for (Personaje[] matrizPersonaje : Datos.matrizPersonajes) {
            for (Personaje personaje : matrizPersonaje) {
                personaje = null;
                
            }
        }
        int contado = 0;
        for (JButton botonesdefensasDisponible : Datos.botonesdefensasDisponibles) {
            if (Datos.defensas.get(contado).getNivelAparicion() <= Datos.nivel){
                botonesdefensasDisponible.setEnabled(true);
            }
            contado += 1;
            
            
        }
        Datos.defensasEnJuego.clear();
        Datos.ZombiesEnJuego.clear();
        Datos.accionMouse = Datos.EstadoHaciendoMouse.NADA;
        Datos.campos = 0;
        Datos.jugando = false;
        Datos.ponePilar(10, 10);
        this.setVisible(false);     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        for (JButton[] jButtons : Datos.matrizBotonesInterfaz) {
            for (JButton jButton : jButtons) {
                jButton.setIcon(null);
            }
            
        }
        for (Personaje[] matrizPersonaje : Datos.matrizPersonajes) {
            for (Personaje personaje : matrizPersonaje) {
                personaje = null;
                
            }
        }
        Datos.defensasEnJuego.clear();
        Datos.ZombiesEnJuego.clear();
        Datos.accionMouse = Datos.EstadoHaciendoMouse.NADA;
        Datos.campos = 0;
        Datos.jugando = false;
        Datos.ponePilar(10, 10);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new VentanaResultados().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JLabel lbl_resultado_zombies;
    public javax.swing.JTextArea txa_resultadod;
    public javax.swing.JTextArea txa_resultadoz;
    // End of variables declaration//GEN-END:variables
}
